default:
  image: php:7.4-cli-alpine

  cache:
    paths:
      - vendor/
      - coverage/

  before_script:
    - apk add --no-cache $PHPIZE_DEPS
    - pecl install timezonedb xdebug
    - docker-php-ext-enable timezonedb xdebug
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

stages:
  - check
  - test

check:
  stage: check
  script:
    - vendor/bin/php-cs-fixer fix --dry-run src
    - vendor/bin/php-cs-fixer fix --dry-run tests
    - vendor/bin/phpstan analyse --no-progress --level 5 src tests

test:
  stage: test
  script:
    - vendor/bin/phpunit --strict-coverage --coverage-html=coverage/
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
